[package]
name = "huffman-coding"
version = "0.1.0"
authors = ["trickypr <trickypr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.6.2"
serde = "1.0.115"